/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.servicetracker.supportdb.models.query;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import java.io.Serializable;
import java.util.Objects;

import com.wavemaker.runtime.data.annotations.ColumnAlias;

public class GetDashboardMetricsResponse implements Serializable {


    @ColumnAlias("label")
    private String label;

    @ColumnAlias("total")
    private Long total;

    public String getLabel() {
        return this.label;
    }

    public void setLabel(String label) {
        this.label = label;
    }

    public Long getTotal() {
        return this.total;
    }

    public void setTotal(Long total) {
        this.total = total;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof GetDashboardMetricsResponse)) return false;
        final GetDashboardMetricsResponse getDashboardMetricsResponse = (GetDashboardMetricsResponse) o;
        return Objects.equals(getLabel(), getDashboardMetricsResponse.getLabel()) &&
                Objects.equals(getTotal(), getDashboardMetricsResponse.getTotal());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getLabel(),
                getTotal());
    }
}
