package com.wavemaker.servicetracker.invoiceservice.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/
import java.io.IOException;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import com.lowagie.text.DocumentException;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.servicetracker.invoiceservice.InvoiceService;
import com.wavemaker.servicetracker.invoiceservice.model.InvoiceRequest;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;

/**
 * Controller object for domain model class {@link InvoiceService}.
 * @see InvoiceService
 */
@RestController
@Api(value = "InvoiceController", description = "controller class for java service execution")
@RequestMapping("/invoice")
public class InvoiceController {

    @Autowired
    private InvoiceService invoiceService;

    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    @PostMapping(value = "/generatePDF", produces = "application/octet-stream")
    public Downloadable generatePDF(@RequestBody InvoiceRequest invoiceRequest) throws IOException, DocumentException {
        return invoiceService.generatePDF(invoiceRequest);
    }
}

