/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.servicetracker.supportdb.controller;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.web.bind.annotation.DeleteMapping;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PatchMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.PutMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RestController;

import com.wavemaker.commons.wrapper.StringWrapper;
import com.wavemaker.runtime.commons.file.manager.ExportedFileManager;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;
import com.wavemaker.tools.api.core.annotations.MapTo;
import com.wavemaker.tools.api.core.annotations.WMAccessVisibility;
import com.wavemaker.tools.api.core.models.AccessSpecifier;
import com.wordnik.swagger.annotations.Api;
import com.wordnik.swagger.annotations.ApiOperation;
import com.wordnik.swagger.annotations.ApiParam;

import com.wavemaker.servicetracker.supportdb.UserLogin;
import com.wavemaker.servicetracker.supportdb.UserRole;
import com.wavemaker.servicetracker.supportdb.service.UserRoleService;


/**
 * Controller object for domain model class UserRole.
 * @see UserRole
 */
@RestController("SupportDB.UserRoleController")
@Api(value = "UserRoleController", description = "Exposes APIs to work with UserRole resource.")
@RequestMapping("/SupportDB/UserRole")
public class UserRoleController {

    private static final Logger LOGGER = LoggerFactory.getLogger(UserRoleController.class);

    @Autowired
	@Qualifier("SupportDB.UserRoleService")
	private UserRoleService userRoleService;

	@Autowired
	private ExportedFileManager exportedFileManager;

	@ApiOperation(value = "Creates a new UserRole instance.")
    @PostMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public UserRole createUserRole(@RequestBody UserRole userRole) {
		LOGGER.debug("Create UserRole with information: {}" , userRole);

		userRole = userRoleService.create(userRole);
		LOGGER.debug("Created UserRole with information: {}" , userRole);

	    return userRole;
	}

    @ApiOperation(value = "Returns the UserRole instance associated with the given id.")
    @GetMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public UserRole getUserRole(@PathVariable("id") Integer id) {
        LOGGER.debug("Getting UserRole with id: {}" , id);

        UserRole foundUserRole = userRoleService.getById(id);
        LOGGER.debug("UserRole details with id: {}" , foundUserRole);

        return foundUserRole;
    }

    @ApiOperation(value = "Updates the UserRole instance associated with the given id.")
    @PutMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public UserRole editUserRole(@PathVariable("id") Integer id, @RequestBody UserRole userRole) {
        LOGGER.debug("Editing UserRole with id: {}" , userRole.getId());

        userRole.setId(id);
        userRole = userRoleService.update(userRole);
        LOGGER.debug("UserRole details with id: {}" , userRole);

        return userRole;
    }
    
    @ApiOperation(value = "Partially updates the UserRole instance associated with the given id.")
    @PatchMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public UserRole patchUserRole(@PathVariable("id") Integer id, @RequestBody @MapTo(UserRole.class) Map<String, Object> userRolePatch) {
        LOGGER.debug("Partially updating UserRole with id: {}" , id);

        UserRole userRole = userRoleService.partialUpdate(id, userRolePatch);
        LOGGER.debug("UserRole details after partial update: {}" , userRole);

        return userRole;
    }

    @ApiOperation(value = "Deletes the UserRole instance associated with the given id.")
    @DeleteMapping(value = "/{id:.+}")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public boolean deleteUserRole(@PathVariable("id") Integer id) {
        LOGGER.debug("Deleting UserRole with id: {}" , id);

        UserRole deletedUserRole = userRoleService.delete(id);

        return deletedUserRole != null;
    }

    /**
     * @deprecated Use {@link #findUserRoles(String, Pageable)} instead.
     */
    @Deprecated
    @ApiOperation(value = "Returns the list of UserRole instances matching the search criteria.")
    @PostMapping(value = "/search")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<UserRole> searchUserRolesByQueryFilters( Pageable pageable, @RequestBody QueryFilter[] queryFilters) {
        LOGGER.debug("Rendering UserRoles list by query filter:{}", (Object) queryFilters);
        return userRoleService.findAll(queryFilters, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of UserRole instances matching the optional query (q) request param. If there is no query provided, it returns all the instances. Pagination & Sorting parameters such as page& size, sort can be sent as request parameters. The sort value should be a comma separated list of field names & optional sort order to sort the data on. eg: field1 asc, field2 desc etc ")
    @GetMapping
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<UserRole> findUserRoles(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering UserRoles list by filter:", query);
        return userRoleService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns the paginated list of UserRole instances matching the optional query (q) request param. This API should be used only if the query string is too big to fit in GET request with request param. The request has to made in application/x-www-form-urlencoded format.")
    @PostMapping(value="/filter", consumes= "application/x-www-form-urlencoded")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<UserRole> filterUserRoles(@ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
        LOGGER.debug("Rendering UserRoles list by filter", query);
        return userRoleService.findAll(query, pageable);
    }

    @ApiOperation(value = "Returns downloadable file for the data matching the optional query (q) request param.")
    @GetMapping(value = "/export/{exportType}", produces = "application/octet-stream")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Downloadable exportUserRoles(@PathVariable("exportType") ExportType exportType, @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query, Pageable pageable) {
         return userRoleService.export(exportType, query, pageable);
    }

    @ApiOperation(value = "Returns a URL to download a file for the data matching the optional query (q) request param and the required fields provided in the Export Options.") 
    @PostMapping(value = "/export", consumes = "application/json")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public StringWrapper exportUserRolesAndGetURL(@RequestBody DataExportOptions exportOptions, Pageable pageable) {
        String exportedFileName = exportOptions.getFileName();
        if(exportedFileName == null || exportedFileName.isEmpty()) {
            exportedFileName = UserRole.class.getSimpleName();
        }
        exportedFileName += exportOptions.getExportType().getExtension();
        String exportedUrl = exportedFileManager.registerAndGetURL(exportedFileName, outputStream -> userRoleService.export(exportOptions, pageable, outputStream));
        return new StringWrapper(exportedUrl);
    }

	@ApiOperation(value = "Returns the total count of UserRole instances matching the optional query (q) request param.")
	@GetMapping(value = "/count")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Long countUserRoles( @ApiParam("conditions to filter the results") @RequestParam(value = "q", required = false) String query) {
		LOGGER.debug("counting UserRoles");
		return userRoleService.count(query);
	}

    @ApiOperation(value = "Returns aggregated result with given aggregation info")
	@PostMapping(value = "/aggregations")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
	public Page<Map<String, Object>> getUserRoleAggregatedValues(@RequestBody AggregationInfo aggregationInfo, Pageable pageable) {
        LOGGER.debug("Fetching aggregated results for {}", aggregationInfo);
        return userRoleService.getAggregatedValues(aggregationInfo, pageable);
    }

    @GetMapping(value="/{id:.+}/userLogins")
    @ApiOperation(value = "Gets the userLogins instance associated with the given id.")
    @WMAccessVisibility(value = AccessSpecifier.APP_ONLY)
    public Page<UserLogin> findAssociatedUserLogins(@PathVariable("id") Integer id, Pageable pageable) {

        LOGGER.debug("Fetching all associated userLogins");
        return userRoleService.findAssociatedUserLogins(id, pageable);
    }

    /**
	 * This setter method should only be used by unit tests
	 *
	 * @param service UserRoleService instance
	 */
	protected void setUserRoleService(UserRoleService service) {
		this.userRoleService = service;
	}

}
