/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.servicetracker.supportdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.IOException;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.context.annotation.Lazy;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.validation.annotation.Validated;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.ObjectReader;
import com.wavemaker.commons.InvalidInputException;
import com.wavemaker.commons.MessageResource;
import com.wavemaker.runtime.commons.file.model.Downloadable;
import com.wavemaker.runtime.data.annotations.EntityService;
import com.wavemaker.runtime.data.dao.WMGenericDao;
import com.wavemaker.runtime.data.exception.EntityNotFoundException;
import com.wavemaker.runtime.data.export.DataExportOptions;
import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.data.expression.QueryFilter;
import com.wavemaker.runtime.data.model.AggregationInfo;

import com.wavemaker.servicetracker.supportdb.Rma;
import com.wavemaker.servicetracker.supportdb.ServiceMode;


/**
 * ServiceImpl object for domain model class ServiceMode.
 *
 * @see ServiceMode
 */
@Service("SupportDB.ServiceModeService")
@Validated
@EntityService(entityClass = ServiceMode.class, serviceId = "SupportDB")
public class ServiceModeServiceImpl implements ServiceModeService {

    private static final Logger LOGGER = LoggerFactory.getLogger(ServiceModeServiceImpl.class);

    @Lazy
    @Autowired
    @Qualifier("SupportDB.RmaService")
    private RmaService rmaService;

    @Autowired
    @Qualifier("SupportDB.ServiceModeDao")
    private WMGenericDao<ServiceMode, Integer> wmGenericDao;

    @Autowired
    @Qualifier("wmAppObjectMapper")
    private ObjectMapper objectMapper;


    public void setWMGenericDao(WMGenericDao<ServiceMode, Integer> wmGenericDao) {
        this.wmGenericDao = wmGenericDao;
    }

    @Transactional(value = "SupportDBTransactionManager")
    @Override
    public ServiceMode create(ServiceMode serviceMode) {
        LOGGER.debug("Creating a new ServiceMode with information: {}", serviceMode);

        ServiceMode serviceModeCreated = this.wmGenericDao.create(serviceMode);
        // reloading object from database to get database defined & server defined values.
        return this.wmGenericDao.refresh(serviceModeCreated);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public ServiceMode getById(Integer servicemodeId) {
        LOGGER.debug("Finding ServiceMode by id: {}", servicemodeId);
        return this.wmGenericDao.findById(servicemodeId);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public ServiceMode findById(Integer servicemodeId) {
        LOGGER.debug("Finding ServiceMode by id: {}", servicemodeId);
        try {
            return this.wmGenericDao.findById(servicemodeId);
        } catch (EntityNotFoundException ex) {
            LOGGER.debug("No ServiceMode found with id: {}", servicemodeId, ex);
            return null;
        }
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public List<ServiceMode> findByMultipleIds(List<Integer> servicemodeIds, boolean orderedReturn) {
        LOGGER.debug("Finding ServiceModes by ids: {}", servicemodeIds);

        return this.wmGenericDao.findByMultipleIds(servicemodeIds, orderedReturn);
    }


    @Transactional(rollbackFor = EntityNotFoundException.class, value = "SupportDBTransactionManager")
    @Override
    public ServiceMode update(ServiceMode serviceMode) {
        LOGGER.debug("Updating ServiceMode with information: {}", serviceMode);

        this.wmGenericDao.update(serviceMode);
        this.wmGenericDao.refresh(serviceMode);

        return serviceMode;
    }

    @Transactional(value = "SupportDBTransactionManager")
    @Override
    public ServiceMode partialUpdate(Integer servicemodeId, Map<String, Object>serviceModePatch) {
        LOGGER.debug("Partially Updating the ServiceMode with id: {}", servicemodeId);

        ServiceMode serviceMode = getById(servicemodeId);

        try {
            ObjectReader serviceModeReader = this.objectMapper.reader().forType(ServiceMode.class).withValueToUpdate(serviceMode);
            serviceMode = serviceModeReader.readValue(this.objectMapper.writeValueAsString(serviceModePatch));
        } catch (IOException ex) {
            LOGGER.debug("There was a problem in applying the patch: {}", serviceModePatch, ex);
            throw new InvalidInputException("Could not apply patch",ex);
        }

        serviceMode = update(serviceMode);

        return serviceMode;
    }

    @Transactional(value = "SupportDBTransactionManager")
    @Override
    public ServiceMode delete(Integer servicemodeId) {
        LOGGER.debug("Deleting ServiceMode with id: {}", servicemodeId);
        ServiceMode deleted = this.wmGenericDao.findById(servicemodeId);
        if (deleted == null) {
            LOGGER.debug("No ServiceMode found with id: {}", servicemodeId);
            throw new EntityNotFoundException(MessageResource.create("com.wavemaker.runtime.entity.not.found"), ServiceMode.class.getSimpleName(), servicemodeId);
        }
        this.wmGenericDao.delete(deleted);
        return deleted;
    }

    @Transactional(value = "SupportDBTransactionManager")
    @Override
    public void delete(ServiceMode serviceMode) {
        LOGGER.debug("Deleting ServiceMode with {}", serviceMode);
        this.wmGenericDao.delete(serviceMode);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public Page<ServiceMode> findAll(QueryFilter[] queryFilters, Pageable pageable) {
        LOGGER.debug("Finding all ServiceModes");
        return this.wmGenericDao.search(queryFilters, pageable);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public Page<ServiceMode> findAll(String query, Pageable pageable) {
        LOGGER.debug("Finding all ServiceModes");
        return this.wmGenericDao.searchByQuery(query, pageable);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager", timeout = 300)
    @Override
    public Downloadable export(ExportType exportType, String query, Pageable pageable) {
        LOGGER.debug("exporting data in the service SupportDB for table ServiceMode to {} format", exportType);
        return this.wmGenericDao.export(exportType, query, pageable);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager", timeout = 300)
    @Override
    public void export(DataExportOptions options, Pageable pageable, OutputStream outputStream) {
        LOGGER.debug("exporting data in the service SupportDB for table ServiceMode to {} format", options.getExportType());
        this.wmGenericDao.export(options, pageable, outputStream);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public long count(String query) {
        return this.wmGenericDao.count(query);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public Page<Map<String, Object>> getAggregatedValues(AggregationInfo aggregationInfo, Pageable pageable) {
        return this.wmGenericDao.getAggregatedValues(aggregationInfo, pageable);
    }

    @Transactional(readOnly = true, value = "SupportDBTransactionManager")
    @Override
    public Page<Rma> findAssociatedRmas(Integer id, Pageable pageable) {
        LOGGER.debug("Fetching all associated rmas");

        StringBuilder queryBuilder = new StringBuilder();
        queryBuilder.append("serviceMode.id = '" + id + "'");

        return rmaService.findAll(queryBuilder.toString(), pageable);
    }

    /**
     * This setter method should only be used by unit tests
     *
     * @param service RmaService instance
     */
    protected void setRmaService(RmaService service) {
        this.rmaService = service;
    }

}
