/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.servicetracker.supportdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.OutputStream;

import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportOptions;

import com.wavemaker.servicetracker.supportdb.models.query.*;

public interface SupportDBQueryExecutorService {

    Page<GetRatingsAggregationResponse> executeGetRatingsAggregation(Pageable pageable);

    void exportGetRatingsAggregation(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetTotalJobRequestsResponse> executeGetTotalJobRequests(Pageable pageable);

    void exportGetTotalJobRequests(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetTotalOutstandingRmasResponse> executeGetTotalOutstandingRMAs(Pageable pageable);

    void exportGetTotalOutstandingRMAs(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetDashboardMetricsResponse> executeGetDashboardMetrics(Pageable pageable);

    void exportGetDashboardMetrics(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

    Page<GetTotalClosedRmasResponse> executeGetTotalClosedRMAs(Pageable pageable);

    void exportGetTotalClosedRMAs(ExportOptions exportOptions, Pageable pageable, OutputStream outputStream);

}
