/*Copyright (c) 2022-2023 wavemaker.com All Rights Reserved.This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance with the terms of the source code license agreement you entered into with wavemaker.com*/
package com.wavemaker.servicetracker.supportdb;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/

import java.io.Serializable;
import java.sql.Date;
import java.util.Objects;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * JobRequest generated by WaveMaker Studio.
 */
@Entity
@Table(name = "`job_request`")
public class JobRequest implements Serializable {

    private Integer id;
    private String jobRequestNo;
    private Integer productSerialId;
    private String problemDescription;
    private Date createdOn;
    private Boolean isRmaCreated;
    private String serviceCenter;
    private String warrantyStatus;
    private ProductSerial productSerial;

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "`id`", nullable = false, scale = 0, precision = 10)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "`job_request_no`", nullable = true, length = 255)
    public String getJobRequestNo() {
        return this.jobRequestNo;
    }

    public void setJobRequestNo(String jobRequestNo) {
        this.jobRequestNo = jobRequestNo;
    }

    @Column(name = "`product_serial_id`", nullable = true, scale = 0, precision = 10)
    public Integer getProductSerialId() {
        return this.productSerialId;
    }

    public void setProductSerialId(Integer productSerialId) {
        this.productSerialId = productSerialId;
    }

    @Column(name = "`problem_description`", nullable = true, length = 255)
    public String getProblemDescription() {
        return this.problemDescription;
    }

    public void setProblemDescription(String problemDescription) {
        this.problemDescription = problemDescription;
    }

    @Column(name = "`created_on`", nullable = true)
    public Date getCreatedOn() {
        return this.createdOn;
    }

    public void setCreatedOn(Date createdOn) {
        this.createdOn = createdOn;
    }

    @Column(name = "`is_rma_created`", nullable = true)
    public Boolean getIsRmaCreated() {
        return this.isRmaCreated;
    }

    public void setIsRmaCreated(Boolean isRmaCreated) {
        this.isRmaCreated = isRmaCreated;
    }

    @Column(name = "`service_center`", nullable = true, length = 255)
    public String getServiceCenter() {
        return this.serviceCenter;
    }

    public void setServiceCenter(String serviceCenter) {
        this.serviceCenter = serviceCenter;
    }

    @Column(name = "`warranty_status`", nullable = true, length = 255)
    public String getWarrantyStatus() {
        return this.warrantyStatus;
    }

    public void setWarrantyStatus(String warrantyStatus) {
        this.warrantyStatus = warrantyStatus;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "`product_serial_id`", referencedColumnName = "`id`", insertable = false, updatable = false, foreignKey = @ForeignKey(name = "`FK_job_request_TO_producQkDPy`"))
    @Fetch(FetchMode.JOIN)
    public ProductSerial getProductSerial() {
        return this.productSerial;
    }

    public void setProductSerial(ProductSerial productSerial) {
        if(productSerial != null) {
            this.productSerialId = productSerial.getId();
        }

        this.productSerial = productSerial;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof JobRequest)) return false;
        final JobRequest jobRequest = (JobRequest) o;
        return Objects.equals(getId(), jobRequest.getId());
    }

    @Override
    public int hashCode() {
        return Objects.hash(getId());
    }
}
